services:
  - type: web
    name: codev-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: "./start-services.sh"
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: PORT
        value: "3000"
      # Добавьте свои переменные окружения:
      # - key: DATABASE_URL
      #   sync: false
      # - key: BOT_TOKEN
      #   sync: false
      # - key: OPENAI_API_KEY
      #   sync: false
